### ISSUE TITLE
Download stats in badge not updating

### ISSUE THREAD

**Issue by jhollist** [metacran/cranlogs.app#14]
@gaborcsardi First, thanks for the great work on this.  It is really useful for me as I get asked often how I can show that my work is getting used.  I have pointed to cranlogs multiple times already!

I am having an issue with the badge in a [README.md](https://github.com/USEPA/lakemorpho/blob/master/README.md).  The badge shows up fine, but the values are not updated.  For instance, the values in the badge on the readme show 1896 total downloads.  But when you ding the site the svg indicates 1980 downloads (as of 5/7/2015).  You appear to be having the same issue on your [README.md](https://github.com/metacran/cranlogs.app/blob/master/README.md).  Total downloads for Rcpp there shows 6017, but badge from cranlogs.r-pkg.org indicates 8462 (as of 5/7/2015).

Again, thanks for you work on this (and all of metacran for that matter).

**Comment by gaborcsardi** [comment]
Hi, initially we did not serve the SVGs with the right HTTP headers, and Github is probably still caching yours. 

I have removed the cached version from the Github cache, so it should be fine now. I have also fixed Rcpp.

We are using the right headers now, so there should be no more problems in the future.

More info: https://help.github.com/articles/why-do-my-images-have-strange-urls/

**Comment by jhollist** [comment]
Thanks!  Cache cleared.
