### ISSUE TITLE
Badge for CRAN version

### ISSUE THREAD

**Issue by sckott** [metacran/cranlogs.app#15]
e.g., https://github.com/hyperium/hyper#hyper

I think it would be useful to give CRAN version in a badge in README's

**Comment by gaborcsardi** [comment]
Great idea! In fact I have already done it a couple of weeks ago. :) 

It is not in cranlogs, though, cranlogs only knows about downloads. See more here: http://www.r-pkg.org/services#badges E.g.

`http://www.r-pkg.org/badges/version/igraph` becomes

![](http://www.r-pkg.org/badges/version/igraph)

**Comment by sckott** [comment]
great, mind if I use it?

**Comment by gaborcsardi** [comment]
No, that's the goal. :) Some people are already using it, e.g. https://github.com/hadley/devtools and `devtools` even has an `use_cran_badge` function now.

**Comment by sckott** [comment]
thanks, glad hadley's incorporated

**Comment by bquast** [comment]
thanks gabor, this is really cool
