### ISSUE TITLE
Requesting png badges, instead of svg. pandoc (pdflatex) hates svg

### ISSUE THREAD

**Issue by sahilseth** [metacran/cranlogs.app#19]
I am trying to compile both html and pdf from a Rmd file.

The pdf fails with the following error:

```
pandoc: Unable to convert image `/var/folders/pt/061nmk8s53x4tw_j92hp4hnr0000gn/T/tex2pdf.6334/c3fd0364f0ccb172153fb6fd829150bca9077120.svgz':
```

Found a few helpful guides to address this issue, most of them focus on embedding svg into pdf documents (rendering Rmd files dirty for HTML output).

Would be awesome if the badge API could include a format option, much like travis does.

```
https://travis-ci.org/sahilseth/flowr.png?branch=master
```

[![Build Status](https://travis-ci.org/sahilseth/flowr.png?branch=master)](https://travis-ci.org/sahilseth/flowr)

**Comment by gaborcsardi** [comment]
I think pandoc should definitely handle SVG files, and I am not planning to add PNGs, as they look much worse. As you can read it here: pandoc will never support svgs (I don't really understand the rationale, though), and this link also gives you a workaround: https://github.com/jgm/pandoc/issues/265
