### ISSUE TITLE
RStudio downloads vs. "total" downloads

### ISSUE THREAD

**Issue by arilamstein** [metacran/cranlogs.app#20]
Thanks for the great package. My limited understanding of CRAN is that RStudio is the only mirror that provides download stats, and that cranlogs stats are from the RStudio server only. Is this correct?

If a package has 100 downloads reported from metacran, is there any way to know what the total number of installs is?

**Comment by gaborcsardi** [comment]
> Thanks for the great package. My limited understanding of CRAN is that RStudio is the only mirror that provides download stats, and that cranlogs stats are from the RStudio server only. Is this correct?

Yes.

> If a package has 100 downloads reported from metacran, is there any way to know what the total number of installs is?

No, afaik.

**Comment by arilamstein** [comment]
Thanks Gabor. I know that you just got funding for a major cran related project. Will that project provide us with a more complete picture of package download stats?

**Comment by gaborcsardi** [comment]
No, it won't. The CRAN mirrors are not giving out data.

**Comment by arilamstein** [comment]
That's too bad. Thanks for the quick response!
