### ISSUE TITLE
Badge for github version

### ISSUE THREAD

**Issue by MansMeg** [metacran/cranlogs.app#21]
Hi!

Great job with these bagdes! I'm only missing a badge to show which version that is in the masterbranch of a github package, for the useres to see fast if there is a new version. I guess this could be done using github API? Any suggestions?

**Comment by gaborcsardi** [comment]
Hi, cranlogs (metacran) is for CRAN packages primarily, so maybe a GitHub version is not that important. You can actually also use GitHub releases for this, and then get a badge from 

https://github.com/badges/shields
https://img.shields.io/github/release/hadley/dplyr.svg

Although it seems to be down right now.

**Comment by MansMeg** [comment]
I totally understand this problem, saw that shields.io needs a server. Maybe the release version of github is as good as it gets.
