### ISSUE TITLE
cranlogs queries are several days behind RStudio's posted CRAN logs

### ISSUE THREAD

**Issue by sfirke** [metacran/cranlogs.app#25]
I notice that `cranlogs::cran_downloads` is several days behind the [CRAN logs posted here](http://cran-logs.rstudio.com/).  Right now those `.gz` files include one for October 4th, but:

```
> cran_downloads("ggplot2", from = "2016-10-01", to = "2016-10-05")
        date count package
1 2016-10-01  5499 ggplot2
2 2016-10-02  5893 ggplot2
3 2016-10-03     0 ggplot2
4 2016-10-04     0 ggplot2
5 2016-10-05     0 ggplot2
```

And https://cranlogs.r-pkg.org/badges/last-day/ggplot2 is showing 5893.  In both cases, this is the October 2nd result.  Is something awry?

**Comment by gaborcsardi** [comment]
Thanks for letting me know.

RStudio used to ping the cranlogs server when a new log was available. They do not ping it any more it seems. 

I'll have to implement some polling.

I bumped it manually now.

**Comment by sfirke** [comment]
Thanks Gabor!
