### ISSUE TITLE
CRAN URL not in canonical form

### ISSUE THREAD

**Issue by mvuorre** [metacran/cranlogs.app#27]
Hi,

Currently, the badge URL gives a NOTE on winbuilder. For example, when using winbuilder on package bmlm:

```
Found the following (possibly) invalid URLs:
  URL: http://cran.rstudio.com/web/packages/bmlm/index.html (moved to https://cran.rstudio.com/web/packages/bmlm/index.html)
    From: README.md
    Status: 200
    Message: OK
    CRAN URL not in canonical form
```

The badge links should probably be in the "canonical CRAN form", e.g.:

<https://cran.r-project.org/package=bmlm>

**Comment by gaborcsardi** [comment]
Thanks! Do you want to submit a PR?

**Comment by mvuorre** [comment]
Sorry, I don't think I'd know how to fix it.
