### ISSUE TITLE
weekly (not daily) download over specific period

### ISSUE THREAD

**Issue by samnet** [metacran/cranlogs.app#29]
As per the example, it is possible to access daily downloads over a given period. E.g., http://cranlogs.r-pkg.org/downloads/daily/2014-01-03:2014-02-03/ggplot2

My goal is to have weekly download volumes for a package over a long period. 

From the result of the above request I can compute weekly volumes, but that means retrieving a lot more information than necessary. If I replace "daily" with "weekly", I get an error (invalid query). Is it at all possible to get weekly data? 

Best

**Comment by gaborcsardi** [comment]
No, not possible currently. You need to add the daily numbers.
