### ISSUE TITLE
Instructions on how to build and setup the project locally

### ISSUE THREAD

**Issue by dirkschumacher** [metacran/cranlogs.app#32]
It would be great to have a section in the README about cloning and building the project locally. I guess this would make it easier for new contributors to fix things (including myself :))

**Comment by gaborcsardi** [comment]
You can't easily do that, because you cannot connect to the database from your local machine.

**Comment by dirkschumacher** [comment]
But could't I setup a local postgres DB instance? The scripts for that seem to be in `db`.

**Comment by gaborcsardi** [comment]
I suppose you could, yeah.

I would need to modify the app, though, because AFAIR right now a DB update pulls down everything that is missing from the DB.... not too hard, though, so yeah, I'll try.

**Comment by dirkschumacher** [comment]
No rush, I would have just liked to test the PR locally before sending it :)

**Comment by gaborcsardi** [comment]
I just deployed it, seems to work.  :)
