### ISSUE TITLE
Data not fetching anymore

### ISSUE THREAD

**Issue by msberends** [metacran/cranlogs.app#34]
I check download counts everyday, but since 7th of August data fetching has stopped. 

Have a look at https://cranlogs.r-pkg.org/downloads/daily/last-month/dplyr or https://cranlogs.r-pkg.org/downloads/daily/last-month/MASS. 

This applies to daily downloads but also the total counts (weekly, monthly and total).

**Comment by Polkas** [comment]
Hi, for the purpose of satisfying curiosity you could download the data directly from RStudio.  
Something like that:
```r
install.packages('pacman')
pacman::p_load(
               doParallel,
               foreach,
               readr            
)
###HERE CHANGE THE WINDOW
DATES = seq.Date(as.Date('2018-08-06'),as.Date('2018-08-16'),1)

cl <- makePSOCKcluster(max(parallel::detectCores()-1,1))
doParallel::registerDoParallel(cl)

Rlogs_merged = foreach(i = 1:length(DATES),.combine = "rbind") %dopar%
{
  my_data = tryCatch(readr::read_csv(paste0("http://cran-logs.rstudio.com/2018/",DATES[i],'.csv.gz'),col_names = c('date','time','size','r_version','r_arch','r_os','package','version','country','ip_id'),col_types =  "ccicccccci"),    
                     error= function(e) data.frame(date=NA , time=NA, size=NA, r_version=NA, r_arch=NA, r_os=NA, package=NA, version=NA, country=NA, ip_id=NA))
  
  my_data
  
}
stopCluster(cl)
```
PS. cranlogs.app offers REST to db built under gz csv files gathered from links like http://cran-logs.rstudio.com/2018/2018-08-16.csv.gz
/MN

**Comment by richard987** [comment]
I noticed that the counts had stopped updating as well, for example:
https://cranlogs.r-pkg.org/badges/grand-total/featurefinder
as well as all the major packages eg
Rcpp, stringi, ggplot2, glue, rlang
on
https://hadley.shinyapps.io/cran-downloads/

**Comment by msberends** [comment]
Yeah, that was basically my point :)

**Comment by richard987** [comment]
Just backing you up there

**Comment by gaborcsardi** [comment]
Thanks, should be OK now.
